# Generated by Django 5.1.4 on 2024-12-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='New',
        ),
    ]
